import pyautogui
import time
import pandas as pd
   
time.sleep(5)
df = pd.read_csv('C:\\Users\\pisit.kae\\Documents\\GitHub\\AutomateInsertDataToAX-JournalName\\GLJournalName - Novocher\\APHGLJN.csv')
# pyautogui.hotkey('alt','tab')
for ind in df.index:
    pyautogui.write(df['JournalName'][ind])
    pyautogui.hotkey('tab')
    pyautogui.write(df['Name'][ind])
    pyautogui.hotkey('tab')
    pyautogui.write(df['Journal type'][ind])
    pyautogui.hotkey('tab')
    pyautogui.hotkey('tab')
    pyautogui.hotkey('tab')
    pyautogui.hotkey('tab')
    pyautogui.hotkey('tab')
    pyautogui.hotkey('tab')
    pyautogui.write(df['NumberSequenceDefault'][ind])
    pyautogui.hotkey('tab')
    pyautogui.write(df['New voucher'][ind])
    pyautogui.hotkey('tab')
    pyautogui.hotkey('tab')
    pyautogui.hotkey('tab')
    if df['Use group voucher'][ind] == 'P' :
        pyautogui.press('space')
    pyautogui.hotkey('tab')
    pyautogui.write(df['GroupVoucher'][ind])
    pyautogui.hotkey('tab')
    pyautogui.hotkey('tab')
    pyautogui.write(df['Account type'][ind])
    pyautogui.hotkey('tab')
    pyautogui.hotkey('tab')
    pyautogui.hotkey('tab')
    pyautogui.write(df['Posting layer'][ind])
    pyautogui.hotkey('tab')
    pyautogui.write('Detail level')
    pyautogui.hotkey('tab')
    pyautogui.write('Fees posting')
    pyautogui.hotkey('tab')
    pyautogui.hotkey('tab')
    pyautogui.hotkey('tab')
    pyautogui.write(df['Currency'][ind]) 
    time.sleep(0.5)
    pyautogui.hotkey('ctrl','n')
    
    print(df['JournalName'][ind], df['Name'][ind],df['NumberSequenceDefault'],df['GroupVoucher'])